baseURL = "/"

title = "おいら屋ファクトリー"

copyright = "&copy <a href=\"https://twitter.com/ebith\">ebith</a> 2012-2017"

theme = "aglaus"
[params]
  dateformat= "January 02, 2006"

hasCJKLanguage = "true"

# disqusShortname = "ebith"
googleAnalytics = "UA-34280150-1"

Paginate = 10
preserveTaxonomyNames = true

enableRobotsTXT = true

defaultContentLanguage = "ja"

[permalinks]
page = "/:slug/"

[blackfriday]
hrefTargetBlank = true
