baseURL = "/"
title = "おいら屋ファクトリー"
copyright = "&copy <a href=\"https://twitter.com/ebith\">ebith</a> 2012-2017"
hasCJKLanguage = true
googleAnalytics = "UA-34280150-1"
paginate = 10
preserveTaxonomyNames = true
enableRobotsTXT = true
defaultContentLanguage = "ja"

theme = "aglaus"
[params]
  dateformat= "January 02, 2006"

[permalinks]
page = "/:slug/"

[blackfriday]
hrefTargetBlank = true
